#!/usr/bin/env bash

emails=$(git log master..HEAD --pretty=format:'%ae' | sort | uniq)
for email in $emails; do
  printf "checking %s\n" "$email"
  if ! curl -s 'https://dco.commento.io/api/has-signed' -d "email=$email" -X POST \
         | jq '.hasSigned' \
         | grep -q true; then
    printf "%s has not signed the DCO: https://dco.commento.io\n" "$email"
    exit 1
  fi
done
